/**
 * update.js - CS2 Vault in-place updater
 * Downloads source files from GitHub only if they differ from local copies.
 * Never touches: node_modules, session.json, prices_cache.json, items.json,
 *                icon_cache.json, collections.json (locally generated)
 */
'use strict';
const https  = require('https');
const fs     = require('fs');
const path   = require('path');
const crypto = require('crypto');

const BASE = 'https://raw.githubusercontent.com/aplcake/cs2-vault/main/';

// Files to check/update from GitHub
const FILES = [
  'server.js',
  'public/index.html',
  'fetch-items.js',
  'patch-items.js',
];

// Files to NEVER overwrite regardless of what GitHub has
const PROTECTED = new Set([
  'session.json',
  'prices_cache.json',
  'icon_cache.json',
  'items.json',
  'storage_cache.json', // locally generated, different per account
  'collections.json',   // locally generated by fetch-items.js
  'node_modules',
  'package.json',
  'package-lock.json',
]);

function get(url) {
  return new Promise((resolve, reject) => {
    https.get(url, { headers: { 'User-Agent': 'CS2Vault/1.0' } }, res => {
      if (res.statusCode === 301 || res.statusCode === 302)
        return get(res.headers.location).then(resolve, reject);
      if (res.statusCode !== 200) {
        res.resume();
        return reject(new Error(`HTTP ${res.statusCode} for ${url}`));
      }
      const chunks = [];
      res.on('data', c => chunks.push(c));
      res.on('end', () => resolve(Buffer.concat(chunks)));
      res.on('error', reject);
    }).on('error', reject);
  });
}

function sha256(buf) {
  return crypto.createHash('sha256').update(buf).digest('hex');
}

async function main() {
  // Version check first
  try {
    console.log('Checking for updates from GitHub...');
    const ver = await get(BASE + 'version.txt');
    console.log('Remote version: ' + ver.toString().trim());
  } catch(e) {
    console.log('Note: version check failed (' + e.message + ')');
    console.log('Trying file-level updates anyway...');
  }

  let updated = 0, skipped = 0, failed = 0;

  for (const file of FILES) {
    if (PROTECTED.has(file)) {
      console.log('  SKIP (protected): ' + file);
      skipped++;
      continue;
    }

    const dest = path.join(__dirname, file);

    // Read local copy if it exists
    let localHash = null;
    if (fs.existsSync(dest)) {
      localHash = sha256(fs.readFileSync(dest));
    }

    // Fetch remote
    let remote;
    try {
      process.stdout.write('  Checking ' + file + '... ');
      remote = await get(BASE + file);
    } catch(e) {
      console.log('FAILED to fetch: ' + e.message);
      failed++;
      continue;
    }

    const remoteHash = sha256(remote);

    if (localHash && localHash === remoteHash) {
      console.log('up to date');
      skipped++;
      continue;
    }

    // Different — write it
    try {
      fs.mkdirSync(path.dirname(dest), { recursive: true });
      fs.writeFileSync(dest, remote);
      console.log(localHash ? 'updated' : 'installed');
      updated++;
    } catch(e) {
      console.log('FAILED to write: ' + e.message);
      failed++;
    }
  }

  console.log(`\nDone: ${updated} updated, ${skipped} unchanged/skipped, ${failed} failed.`);
  if (updated > 0) console.log('Restart CS2 Vault to apply changes.');
}

main().catch(e => { console.error('Fatal:', e.message); process.exit(1); });
